spring:
  application:
    name: rabet
  datasource:
     url: jdbc:postgresql://localhost:5432/medicare
     username: postgres
     password: 1997
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update